local Bulbizarre = require("pok/bulbizarre")
local Herbizarre = require("pok/herbizarre")
local Florizarre = require("pok/florizarre")
local Salameche = require("pok/salameche")
local Mackogneur = require("pok/mackogneur")
local Abra = require("pok/abra")
local Alakazam = require("pok/alakazam")
local Caninos = require("pok/caninos")
local Carabaffe = require("pok/carabaffe")
local Carapuce = require("pok/carapuce")
local Dracaufeu = require("pok/dracaufeu")
local Hypocean = require("pok/hypocean")
local Hypotrempe = require("pok/hypotrempe")
local Insecateur = require("pok/insecateur")
local Kadabra = require("pok/kadabra")
local Kangourex = require("pok/kangourex")
local Leveinard = require("pok/leveinard")
local Machoc = require("pok/machoc")
local Machopeur = require("pok/machopeur")
local Miaouss = require("pok/miaouss")
local MMime = require("pok/mmime")
local Pikachu = require("pok/pikachu")
local Ratata = require("pok/ratata")
local Ratatac = require("pok/ratatac")
local Reptincel = require("pok/reptincel")
local Tortank = require("pok/tortank")

return {
    Bulbizarre = Bulbizarre,
    Herbizarre = Herbizarre,
    Florizarre = Florizarre,
    Salameche = Salameche,
    Mackogneur = Mackogneur,
    Abra = Abra,
    Alakazam = Alakazam,
    Caninos = Caninos,
    Carabaffe = Carabaffe,
    Carapuce = Carapuce,
    Dracaufeu = Dracaufeu,
    Hypocean = Hypocean,
    Hypotrempe = Hypotrempe,
    Insecateur = Insecateur,
    Kadabra = Kadabra,
    Kangourex = Kangourex,
    Leveinard = Leveinard,
    Machoc = Machoc,
    Machopeur = Machopeur,
    Miaouss = Miaouss,
    MMime = MMime,
    Pikachu = Pikachu,
    Ratata = Ratata,
    Ratatac = Ratatac,
    Reptincel = Reptincel,
    Tortank = Tortank,
}